apiVersion: v1
kind: Secret
metadata:
  name: secrets-production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgICAgICJyZWdpc3RyeS5pbnRlcm5hbC51aWEubm8iOiB7DQogICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlpXRnFZVzFoT2twaGNHRnVkSFZ5Wlc0eU1ESXpMZz09Ig0KICAgICAgICAgICAgfQ0KICAgIH0NCn0=
